# Generated by Django 3.2 on 2023-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Profession', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Skill', verbose_name='Навык'),
        ),
    ]
