# Generated by Django 3.2 on 2023-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужской', max_length=7),
            preserve_default=False,
        ),
    ]
