# Generated by Django 3.2 on 2023-01-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230126_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.profession', verbose_name='Специальность'),
        ),
    ]
