# Generated by Django 3.2 on 2023-01-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230126_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=7),
        ),
    ]
