# Generated by Django 3.2 on 2023-02-15 12:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[users.validators.UsernameRegexValidator(), users.validators.username_me], verbose_name='Никнейм'),
        ),
    ]
