# Generated by Django 3.2 on 2023-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя и Фамилия'),
        ),
    ]
