# Generated by Django 3.2 on 2023-03-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_url',
        ),
    ]
