# Generated by Django 3.2 on 2023-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/images/default_image.png', null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
