# Generated by Django 3.2 on 2023-02-15 12:57

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Кривой никнейм', regex='[a-zA-Z0-9_\\-\\.@]{3,20}$'), users.validators.username_me], verbose_name='Никнейм'),
        ),
    ]
