# Generated by Django 3.2 on 2023-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230127_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Формат даты YYYY.MM.DD', null=True, verbose_name='Дата рождения'),
        ),
    ]
