# Generated by Django 3.2 on 2023-02-15 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Кривой никнейм', regex='[a-zA-Z0-9_\\-\\.@]{3,20}$')], verbose_name='Никнейм'),
        ),
    ]
